Implement where and clause
penberg/limbo pull request #147
Opened 2024-07-15 15:37 UTC by benclmnt

Related to #123

2024-07-15 16:00 UTC, jussisaurio commented on core/vdbe.rs
> +                            state.pc = target_pc;
I guess these instructions should also have a register for `SQLITE_JUMPIFNULL`, but probably not a thing to concentrate on right now

2024-07-15 16:01 UTC, jussisaurio approved these changes

2024-07-15 16:03 UTC, penberg commented
Looks pretty straight-forward. @pereman2, are you OK with this as well?

2024-07-15 20:48 UTC, pereman2 requested changes
Sorry but i implement https://github.com/penberg/limbo/pull/152. The rest maybe we can keep

2024-07-15 20:48 UTC, pereman2 commented on core/vdbe.rs
> +                        (OwnedValue::Integer(lhs), OwnedValue::Float(rhs)) => {
Are these operations needed? We can just overlod operator == like with sums.

2024-07-16 05:04 UTC, penberg commented
Hey @benclmnt, sorry for the hopefully trivial conflict in `all.test`. @pereman2, please re-review this.

2024-07-16 05:52 UTC, benclmnt commented
> Hey @benclmnt, sorry for the hopefully trivial conflict in `all.test`. @pereman2, please re-review this.

no worries, fixed it

2024-07-16 18:10 UTC, pereman2 approved these changes

2024-07-16 18:35 UTC, merged