Implement the `UnixEpoch` function
penberg/limbo pull request #273
Opened 2024-08-05 01:49 UTC by rajivharlalka

- [ ] Add the modifier parameter in function.

2024-08-05 01:53 UTC, rajivharlalka commented
@penberg I was quite unsure of how I should add tests for this function.

2024-08-05 05:10 UTC, penberg commented
@rajivharlalka You can test the function with a modifier:

```
sqlite> SELECT unixepoch('2024-08-05');
1722816000
```

Of course, you won't be able to cover all of the functionality in `unixepoch()` but that's OK.

2024-08-05 06:22 UTC, sonhmai commented
hi @rajivharlalka, maybe [this PR 252](https://github.com/penberg/limbo/commit/e6985c1380ca97527f89433e08aa579a05f968aa#diff-a046d58ab24eee8207f0ce3199f8d0a609edcef9c24b8ed7f242f7a60e6c1e61) can serve as an example. 

The test can be added to `testing/scalar-functions.test` and executed with `make test`.

The tests from `sqlite` can be referenced https://github.com/sqlite/sqlite/blob/f2b21a5f57e1a1db1a286c42af40563077635c3d/test/date3.test#L36 and https://github.com/sqlite/sqlite/blob/f2b21a5f57e1a1db1a286c42af40563077635c3d/test/date.test#L604

Hope it helps!

2024-08-05 07:17 UTC, rajivharlalka commented
@sonhmai that looks quite a neat approach for testing the function. Would implement it in some time. Thanks for the reference.

2024-08-18 14:12 UTC, penberg commented
Hey @rajivharlalka! Are you still working on this?

2024-08-19 08:16 UTC, rajivharlalka commented
Hi @penberg ,  Sorry had been a little drifted from this PR. would try to complete it asap as only a modifier needs to be added.

2024-08-25 15:28 UTC, rajivharlalka commented
@penberg I feel that the modifiers are quite common among all time functions and should be taken care seperatly. Can review and merge this PR for now.

2024-08-26 01:17 UTC, sonhmai requested changes

2024-08-26 01:17 UTC, sonhmai commented on testing/scalar-functions.test
could you rebase main and move these tests to `testing/scalar-functions-datetime.test`? 
the tests of datetime functions are now moved to this file.

2024-08-26 01:21 UTC, sonhmai commented
@rajivharlalka can we also change `COMPAT.md` file to note that `unixepoch` function is now partially supported?

as a side note, we added modifiers in https://github.com/penberg/limbo/pull/305 for `time(..)` function, integrations with other datetime functions incl. `unixepoch` is likely similar.

2024-08-30 14:35 UTC, penberg commented
Hey @rajivharlalka, would you be able to move the tests to the new file as pointed out by @sonhmai?

2024-08-30 15:07 UTC, rajivharlalka commented
sorry @sonhmai , somehow missed the notification about your review. Have moved the test into the `*-datetime` test file. 
Regarding the modifiers, I will try to take it up in another PR if it would be possible for me, don't want to stall this one as it's already been long.

2024-08-30 15:26 UTC, closed without merging