Index lookup support
penberg/limbo pull request #312
Opened 2024-09-01 13:44 UTC by ajayaa

Adds support for parsing index structure

2024-09-02 11:55 UTC, pereman2 reviewed
So this only creates an index table in memory and you cannot perform lookup optimizations too? Can you add a description to the pr to clarify these things?

Write path I imagine will take some more time, currently I'm working on the whole write path for limbo.

PS: you can use a different tag to reference an issue instead of `References`, like `Fixes:`, this way it is automatically closed. (reference https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

2024-09-02 21:03 UTC, travenin requested changes
I compiled the code and saw some new compiler warnings about unused thingies. I commented them to the code. New warnings are not a big deal since we already have dozens of them, but it would be good to avoid new warnings. Especially unused imports are easy to fix.

2024-09-03 06:46 UTC, ajayaa commented on core/schema.rs
> +    pub unique: bool,
Yes - that's correct.

2024-09-03 06:46 UTC, ajayaa commented on core/schema.rs
> +    pub order: Order,
Yes.

2024-09-03 10:09 UTC, closed without merging